### ISSUE TITLE
Clicking on Windows 10 and dragging from browser file picker it induces to not responding

### ISSUE THREAD

**Issue by albertolive** [okonet/react-dropzone#144] opened 2016-03-02 10:41 UTC
Hi,

We have found that when we're on Windows 10, clicking Dropzone brings up the browser file picker. Then if we drag and drop a image from there, the main browser collapses.

It happens with all major browsers. 

Thanks for advance!

**Comment by okonet** [comment] 2016-03-02 11:53
Collapses? Can you make a screen video? Does it relate to the component? Sounds more as a OS issue with drag'n'drop and file input.

**Comment by albertolive** [comment] 2016-03-02 16:13
When I say collapses, I'm referring that the browser stops responding. Ok, I'm gonna make a screen video to show you.

**Comment by mantagen** [comment] 2016-05-04 19:52
Hi, has anyone else experienced this? Am considering using react-dropzone on a project but if it is not compatible with a modern browser in windows 10 then won't be able to use it.

**Comment by okonet** [comment] 2016-05-05 07:54
It is compatible per spec with IE10+ but as any open source project might still have issues and bugs.

**Comment by tbutman** [comment] 2016-06-21 22:59
I've found that on IE10 the onFileSelect callback that I pass to the onDrop prop of my Dropzone component is being fired immediately when I click on the dropzone (or open it via this.refs.dropzone.open() ). The component works as expected on all other browsers.

**Comment by okonet** [comment] 2016-06-22 10:56
@albertolive I've just tried to reproduce it on Win7 in IE10 without any luck. Check out http://okonet.ru/react-dropzone/ 

I'm also not sure what are you doing, since when the file dialog appears, it is modal so you have to choose a file with it, not by draggin it somewhere. Although I tried dragging it to the page, but browsers displays a mouse cursor suggesting this action isn't possible. Am I doing it wrong? 

Pleas make a screen video of your issue and describe exact steps to reproduce it. I'm closing it until then.

@tbutman does this related to this issue? If not, please file another one. Also, when filing it, please create a demo that I can quickly check out. I don't have much time to work on this ATM.

**Closed by okonet** 2016-06-22 10:56 UTC

**Comment by sercanov** [comment] 2016-09-23 08:11
+1 with @albertolive 

I'm having issue with Windows 10 + Chrome, tried on 3 different machines. Works fine on macOS.
onDrop event is not fired when file dragged and it freezes the tab.

`<Dropzone accept='application/json' onDrop={this.onDrop}>`

**Comment by sercanov** [comment] 2016-09-23 08:30
Its related to `accept='application/json'` , removed it and it works fine now.

**Comment by sonaye** [comment] 2017-11-08 01:55
What could possibly cause this to happen? is there a way around it where we can keep enforcing json files only?

**Comment by sonaye** [comment] 2017-11-08 01:57
Just got a bug report stating that this occurs only on Windows 10 Chrome.

**Comment by bgeihsgt** [comment] 2018-01-29 19:35
We have run into this on Windows too. The underlying problem is that the incoming file has a type of `''`. 

On Windows, the browser relies on OS file associations to properly set MIME types https://stackoverflow.com/questions/1201945/how-is-mime-type-of-an-uploaded-file-determined-by-browser -- if there isn't a default program set/file association set, the browser just shrugs its shoulders and doesn't set a MIME type. That then fails the `accept` filter on the Dropzone component, yielding a no-op.

I wonder if a good alternative to `accept` would be to also have an optional `extensions` prop that only accepts certain file extensions. There's no real risk there given the MIME type is determined by the extension anyway. Thoughts?

**Comment by johisco** [comment] 2018-10-19 11:46
Hmmm don´t know if this is stilll an issue! But Im running in to something similar... I've created an electron app that uses react-dropzone. 

It works perfect on mac, but on windows I doesn't seem able to drop a file in the dropzone i only get the forbidden icon as I hover over the drop area with a file? Any thoughts ?

**Comment by RamAtDatanchor** [comment] 2018-12-11 04:08
> Hmmm don´t know if this is stilll an issue! But Im running in to something similar... I've created an electron app that uses react-dropzone.
> 
> It works perfect on mac, but on windows I doesn't seem able to drop a file in the dropzone i only get the forbidden icon as I hover over the drop area with a file? Any thoughts ?

did you find any solution @johisco - I see this on Electron on Windows, electron on Mac has no problem whatsoever

**Comment by RamAtDatanchor** [comment] 2018-12-11 13:40
If you are running the electron app as administrator, it won't allow you drag and drop. Thats the case with any windows application like mspaint. I built the electron package as a normal user in non-adminstrator powershell and the built application did allow me to drag and drop.

Its not the problem with the electron but with how Windows separates administrative and non administrative process
