### ISSUE TITLE
assign id and name to drag component setting blank to id value

### ISSUE THREAD

**Issue by vksvicky** [okonet/react-dropzone#454] opened 2017-07-05 19:36 UTC
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
-

**If the current behavior is a bug, please provide the steps to reproduce.**

1. When I add a 'name' and 'id' to the inputAttributes
2. Drag-Drop a file, and perform an operation and inspect document.getElementById("fileUpload").value, result is ""
3. When I click on the Drag-drop area and attach a file, and perform an operation and inspect document.getElementById("fileUpload").value result is "c:\fakepath\file.txt"

**What is the expected behavior?**
1. When I drag-and-drop, and perform an operation and inspect document.getElementById("fileUpload").value, result should be "c:\fakepath\file.txt"

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not sure its a feature/could be a defect depending on the scenario. The motivation is that when posting to Java service I am reading id,m but when I drag-and-drop cannot get the value from id.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
OS: Windows 7
Browsers: Chrome 48.x+, IE 9+, FF 47.x+; Safari 9.x+
react-dropzone version: developer build

**Comment by okonet** [comment] 2017-07-27 12:20
I think this is a duplicate of https://github.com/okonet/react-dropzone/issues/131. If you have a solution for this, feel free to create a PR.

**Closed by okonet** 2017-07-27 12:20 UTC
