### ISSUE TITLE
Unknown props warning with React 15.2

### ISSUE THREAD

**Issue by mikecousins** [okonet/react-dropzone#196] opened 2016-07-06 17:10 UTC
If you use react-dropzone with React 15.2 you now get warnings that look like:

```
warning.js:44 Warning: Unknown props `disableClick`, `disablePreview` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Dropzone)
    in Dropzone (created by ComposePage)
    in div (created by ComposePage)
    in div (created by ComposePage)
    in div (created by ComposePage)
    in div (created by ComposePage)
    in div (created by ComposePage)
    in div (created by ComposePage)
    in ComposePage (created by RouterContext)
```

The React team says this will cause problems in the next major version of React: https://github.com/facebook/react/issues/7152

**Comment by okonet** [comment] 2016-07-06 18:29
Duplicate of #193

**Closed by okonet** 2016-07-06 18:29 UTC
