### ISSUE TITLE
Bug: Version 3.7.1 causes Module not found error

### ISSUE THREAD

**Issue by jakub-c** [okonet/react-dropzone#262] opened 2016-11-01 10:26 UTC
The fix is to fall back to version 3.7.0
Happens using: Webpack 1.x

**Comment by danieloliveira079** [comment] 2016-11-01 10:35
As far as I can see there is an issue related to babel-plugin-add-module-exports.

Possible it is not been detected due to Travis CI is using cached node_modules folder.

Running `npm run build` I got this error saying that add-module-exports is missing.

After installing it manually I managed to build the project and got the dist folder correctly.

**Comment by okonet** [comment] 2016-11-01 10:37
Duplicate of #261

**Comment by okonet** [comment] 2016-11-01 10:37
It's fixed in https://github.com/okonet/react-dropzone/releases/tag/v3.7.2

**Closed by okonet** 2016-11-01 10:37 UTC
