### ISSUE TITLE
Using `accept` for certain file types doesn't work

### ISSUE THREAD

**Issue by aaronbeall** [okonet/react-dropzone#241] opened 2016-09-23 18:40 UTC
I'm trying to only accept `.doc`, `.xls`, and `.xlsx`, but when I drag the files over `Dropzone` it rejects it. It seems that the `.type` property in the `DataTransfer` comes though blank (an empty string) for those files. If I accept all mime-types, then after dropping the file I get the file name, but still no `type`. 

Is there anything that can be done to fix or help with this issue? Right now I'm looking into just not using `accept` in `Dropzone` and instead doing a simple file extension check *after* drop.

**Comment by okonet** [comment] 2016-09-26 09:04
What browser are you using? I'm using File API and here is the [MDN article on that](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications) that uses `type` property. So I guess, the problem is that your browser doesn't deliver this information.

**Comment by aaronbeall** [comment] 2016-09-26 13:47
I'm using Chrome. A colleague saw the same issue in Chrome but also tried a different browser (I think FireFox) and saw different behavior. Again, the `type` is only missing for certain files in Chrome. This seems to be a known limitation of the File API. Disappointing!

So the question for this library, I suppose, is whether you want to deal with this problem in any helpful way. For example right now the implementation of `accept` is not reliable cross-browser. You could provide a post-drop file-extension filter which would work cross browser (this is what we're doing manually.) Otherwise it should just be noted that `accept` cannot be relied on for all file types.

**Comment by okonet** [comment] 2016-09-27 19:00
I definitively don't want this to be a part of this library, TBH :)

But I'm gladly accepting PRs to the README that make this clear.

**Comment by aaronbeall** [comment] 2016-09-27 20:00
Yeah I feel you. :) It would be helpful and not necessarily specific to anything if the component had a few options for validation (like `validate-trigger: drag | drop` and `accept-extensions: Array`), or a custom validation hook. As it is we're not able to use the built-in validation feature. I'll work on an enhancement and possibly submit a PR.  👍

**Comment by okonet** [comment] 2016-09-27 20:15
This is the duplicate of #104 then

**Closed by okonet** 2016-09-27 20:15 UTC

**Comment by Philin-Anton** [comment] 2016-10-20 20:12
hello when can we expect a new version of npm module with these changes?

**Comment by Shuvo-Gain** [comment] 2022-11-09 08:47
why accpet attr is saying [object object ] when passing accept props as same as ract-dropzone docs?
