### ISSUE TITLE
Accpets files dropped of the wrong MIME type?

### ISSUE THREAD

**Issue by awhillas** [okonet/react-dropzone#145] opened 2016-03-03 21:03 UTC
The CSS changes to red but if a different file is dropped on it it still accepts it?

**Comment by okonet** [comment] 2016-03-04 08:09
Duplicate of #138?

**Comment by cgodkin** [comment] 2016-03-16 15:23
Hi Okonet,

After looking at the code, I think I see what's wrong here.  I think that isDragActive and isDragReject are set correctly only with Chrome because, as you mention in the comments, onDragEnter() gets the transfer info only on Chrome.  On Firefox or IE 11, dataTransferItems will be empty which causes allFilesAccepted() to always return true.

I think it would be a good idea to recompute isDragActive and isDragReject inside onDrop() so that the rejectStyle is correctly applied in the next render.  What do you think?

This is a great little package.  Thanks a lot for publishing it.

**Comment by okonet** [comment] 2016-04-04 09:24
Let's start with tests here since I don't quite understand what's the issue is about from the given description. Mind creating a PR?

**Comment by tmarshall** [comment] 2016-05-11 03:33
Ran into this as well, will put up a PR

**Closed** 2016-06-14 15:06 UTC
