### ISSUE TITLE
It will be nice to have already built js file

### ISSUE THREAD

**Issue by klishevich** [okonet/react-dropzone#168] opened 2016-04-21 15:29 UTC
I am using React.js without node, so I will appliciate much if you add dist folder with react-dropzone.js file

**Comment by okonet** [comment] 2016-04-21 18:10
Duplicate of #61

**Closed by okonet** 2016-04-21 18:10 UTC

**Comment by peeinears** [comment] 2016-05-10 05:20
+1. I think this would be really great.

**Comment by littlebee** [comment] 2017-05-01 18:52
+1  I think you underestimate how many applications are using react without using browserify or webpack, or as is our case, using AMD.
