### ISSUE TITLE
Allow accept prop to have not only string but also an array.

### ISSUE THREAD

**Issue by collamo** [okonet/react-dropzone#376] opened 2017-03-09 16:11 UTC
Hi there,
Thanks for your work, this component is helping me a lot.

I have one request.
Since [ attr-accept ](https://github.com/okonet/attr-accept/blob/master/src/index.js) allows to have multiple accept file types. 
I think the propTypes of ``` accept ``` needs to be 
```
accept : React.PropTypes.oneOfType([
    React.PropTypes.string,
    React.PropTypes.array,
])
```
instead of
```
accept: React.PropTypes.string,
```

Thanks!

**Comment by okonet** [comment] 2017-03-09 16:17
Duplicate of #243 and #329

**Closed by okonet** 2017-03-09 16:17 UTC
