### ISSUE TITLE
[Question] Filesize

### ISSUE THREAD

**Issue by nparsons08** [okonet/react-dropzone#192] opened 2016-06-30 04:54 UTC
How can I tell the filesize (in megabytes) and/or prevent files of a certain size (>5MB) from being uploaded?

**Comment by okonet** [comment] 2016-06-30 09:41
Duplicate of #104?

**Comment by okonet** [comment] 2016-08-19 08:29
See https://github.com/okonet/react-dropzone/pull/202

**Closed by okonet** 2016-08-19 08:29 UTC
Labels: question
