### ISSUE TITLE
When I am using this libiary with the Immutable.js, something losing when i set the state

### ISSUE THREAD

**Issue by devalDaimin** [okonet/react-dropzone#368] opened 2017-03-03 03:03 UTC
like this, when the onDrop(acceptedFiles, rejectedFiles) method is called I set the array of accepted to the state  that is  formed by Immutable data, but actually the accepted file data in the state only has the preview, others like size,type...is losing！ 
are there someone meet this problem ?

**Comment by okonet** [comment] 2017-03-03 06:05
Sorry but I'm closing it since it's not really related to the library and it's not a bug. Please ask questions on StackOverflow.

**Closed by okonet** 2017-03-03 06:05 UTC
