### ISSUE TITLE
Dropzone not accepting .doc, .docx files when we use MIME types in supported file formats

### ISSUE THREAD

**Issue by srikanth-pmap** [okonet/react-dropzone#448] opened 2017-06-23 09:18 UTC
**Do you want to request a *feature* or report a *bug*?**

 I want to report a bug in current version

**What is the current behavior?**

Not accepting .doc, .docx files when supplied mime types

**If the current behavior is a bug, please provide the steps to reproduce.**

1. in supported file types i have given MIME types, but dropzone was rejecting .doc, .docx files.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

 Browser : chrome latest tversion
 Dropzone: 3.13.3

**Comment by okonet** [comment] 2017-06-23 09:48
Duplicate of https://github.com/okonet/react-dropzone/issues/276

**Closed by okonet** 2017-06-23 09:48 UTC
