### ISSUE TITLE
Run the sample error

### ISSUE THREAD

**Issue by wm20111003** [okonet/react-dropzone#272] opened 2016-11-08 09:47 UTC
node version v6.5.0
react version v15.3.2
Run the sample error

![image](https://cloud.githubusercontent.com/assets/10558850/20094125/e06e15f6-a5da-11e6-861f-c57dcae617b6.png)

**Comment by okonet** [comment] 2016-11-08 09:57
Duplicate of #209

**Closed by okonet** 2016-11-08 09:57 UTC
