### ISSUE TITLE
Cannot find module "React"

### ISSUE THREAD

**Issue by Mistereo** [okonet/react-dropzone#158] opened 2016-04-04 12:40 UTC
Seems like v3.3.3 just broke my build.
```console
index.js:3Uncaught Error: Cannot find module "React"
```

**Comment by okonet** [comment] 2016-04-04 13:15
I'm on it. Thanks

**Comment by okonet** [comment] 2016-04-04 13:18
Duplicate of #159

**Closed by okonet** 2016-04-04 13:18 UTC
