### ISSUE TITLE
How is maxSize supposed to work?

### ISSUE THREAD

**Issue by teckore** [okonet/react-dropzone#240] opened 2016-09-22 17:34 UTC
Hi, 

I am trying to set the maxSize for the user to upload, however no matter what value I put, it still allows me to put any size images into the box  Any help would be appreciated, thanks!

**Comment by okonet** [comment] 2016-09-22 17:59
Please provide browser and lib version you're using. A repository with there I can reproduce the issue would also help.

**Comment by teckore** [comment] 2016-09-22 18:02
Using Google Chrome Browser, and the version of dropzone I am using is 3.5.3

Current I am using it as follow: 

`<Dropzone onDrop={this.handleOnDrop} multiple={false} maxSize={500000}>
	                     <div style={styles.innerbox}>drop and drag files here</div>
	                  </Dropzone>`

**Comment by okonet** [comment] 2016-09-28 07:04
Dropzone doesn't handle uploading. It will reject files that are too big though. Or am I missing something?

**Comment by th3fallen** [comment] 2016-09-30 15:52
this is not working as expected for me either, i have set my maxSize at 200 to test and no matter the size of the image i drop it still calls the ondrop method or am i missing something?

**Comment by teckore** [comment] 2016-09-30 18:41
It's an odd issue. When I set it as maxSize="500000" on my local machine, it let me upload the file. However, I have a buddy that used that same format and it restricted the upload for him.

**Comment by okonet** [comment] 2016-09-30 19:19
@teckore why are you passing it as a string? Or it is a wrong example here?

**Comment by DimitriMikadze** [comment] 2016-10-06 11:54
Dropzone is just rejecting files that are larger then specified in maxSize. I think it would be more user friendly to give some error message regarding size

**Comment by okonet** [comment] 2016-10-06 12:21
You can do it with `onDropRejected` callback

**Comment by DimitriMikadze** [comment] 2016-10-06 13:18
can you explain how to use it, can't find info regarding that function, thanks!

**Comment by okonet** [comment] 2016-10-06 13:33
See https://github.com/okonet/react-dropzone/blob/master/src/index.js#L117

Same ay you'd use `onDrop`

**Comment by okonet** [comment] 2016-10-06 13:33
Documentation PRs are welcome BTW

**Comment by th3fallen** [comment] 2016-10-06 13:34
@DimitriMikadze here's a real world example of how i used it

```

  onDrop = (file) => {
    this.setState({ savingAvatar: true });
    this.props.uploadAvatar(this.props.user, file[0])
      .then(res => {
        if (!isUndefined(res) && res.error) {
          this.setState({ savingAvatar: false });
          return this.props.errorNotice('There was an error uploading avatar!', { duration: 3000 });
        }
        this.setState({ savingAvatar: false });
        return this.props.successNotice('Avatar upload complete!');
      });
  }

  onDropRejected = () => {
    return this.props.errorNotice('Maximum file upload size is 2MB');
  }

  render() {
    return (
      <div className="container" id="profile-avatar">
        <ImageDrop onDrop={this.onDrop} onDropRejected={this.onDropRejected} maxSize={2097152}>
```

**Comment by DimitriMikadze** [comment] 2016-10-06 13:52
thanks!

**Comment by okonet** [comment] 2016-12-23 16:26
Right now it's not possible to say how big the filesize is until user drops the file. So, dropzone will act as it would accept it but when you drop it, it will reject the file.

I don't know the way to overcome this and any help would be appreciated. I'm closing it since now it's working as expected.

**Closed by okonet** 2016-12-23 16:26 UTC

**Comment by Haraldson** [comment] 2020-06-30 09:55
Is there any way to handle this same scenario, but for the click-and-browse interaction? Everything seems to be centered around dropping files, but as long as this is not the only available interaction, users will still be able to circumvent the specified `maxSize`.
