### ISSUE TITLE
Error when drag/dropping DOM elements

### ISSUE THREAD

**Issue by olalonde** [okonet/react-dropzone#162] opened 2016-04-05 07:49 UTC
When drag/dropping DOM elements into the drop zone, I get the following error:

```
index.js:131 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```

Expected behaviour would be to ignore DOM elements.

**Comment by okonet** [comment] 2017-01-20 14:52
Duplicate of #255

**Closed by okonet** 2017-01-20 14:52 UTC
