### ISSUE TITLE
this.refs.dropzone.open() can't get invoked in a Promise().then()

### ISSUE THREAD

**Issue by bfwg** [okonet/react-dropzone#122] opened 2015-12-29 14:03 UTC
To reproduce the bug
Try this:
```js
new Promise((res, rej) => {
    //Simulate a Async promise
    setTimeout(() => {
        res('ok');
    }, 1000);
})
.then(() => {
   //call dropzone.open in then()
    this.refs.dropzone.open();
});
```
Nothing happen after open is called.

Help Thanks.

**Comment by okonet** [comment] 2015-12-30 10:40
1. Did you set the ref on your `<Dropzone>` element as in example?
1. I'll update the example to the callback version instead of string ref. See https://facebook.github.io/react/docs/more-about-refs.html

**Comment by bfwg** [comment] 2015-12-31 13:12
I did set the ref as in the example.

What I'm trying to do is user has to login to upload. So the open() has to called in side a then or a callback.

This is what I tried: once I put open() outside of then() it works fine but if I put it inside then, it is not working.

**Comment by okonet** [comment] 2016-01-11 10:52
I've just tried the following example and everything worked fine so I'm closing this one for now. If you still having issues, please create a working example (separate repository or gist) so I can try it out quickly.

```
import React from 'react';
import ReactDOM from 'react-dom';
import Dropzone from 'react-dropzone';

const style = {
    borderWidth: 2,
    borderColor: 'black',
    borderStyle: 'dashed',
    borderRadius: 4,
    margin: 30,
    padding: 30,
    width: 200,
    transition: 'all 0.5s'
};

const activeStyle = {
    borderStyle: 'solid',
    backgroundColor: '#eee',
    borderRadius: 8
};

class DropzoneDemo extends React.Component {

    constructor(props, context) {
        super(props, context);
        this.state = {
            files: []
        };
    }

    onDrop(files) {
        console.log('Received files: ', files);
        this.setState({
            files: files
        });
    }

    showFiles() {
        const { files } = this.state;

        if (!files.length) {
            return null;
        }

        return (
            <div>
                <h3>Dropped files: </h3>
                <ul>
                    {
                        files.map((file, idx) => {
                            return (
                                <li key={idx}>
                                    <img src={file.preview} width={100}/>
                                    <div>{file.name + ' : ' + file.size + ' bytes.'}</div>
                                </li>
                            )
                        })
                    }
                </ul>
            </div>
        );
    }

    openAfter() {
        new Promise((res, rej) => {
            //Simulate a Async promise
            setTimeout(() => {
                res('ok');
            }, 1000);
        }).then(() => {
            //call dropzone.open in then()
            this.refs.dropzone.open();
        });
    }

    render() {
        return (
            <div>
                <button onClick={this.openAfter.bind(this)}>Open...</button>
                <Dropzone onDrop={this.onDrop.bind(this)}
                          ref="dropzone"
                          style={style}
                          activeStyle={activeStyle}>
                    Try dropping some files here, or click to select files to upload.
                </Dropzone>
                {this.showFiles()}
            </div>
        );
    }
}

ReactDOM.render(<DropzoneDemo />, document.getElementById('example'));

module.exports = DropzoneDemo;
```

**Closed by okonet** 2016-01-11 10:52 UTC

**Comment by bfwg** [comment] 2016-01-13 05:26
I'm sorry as this might be annoying.
Mine look like this but dropzone is not opening when I try to call ```this.props.submit();``` Which is ```onSubmitLogin()``` in Main Component but everything else is firing except ```this.refs.dropzone.open();```.

```js 
const {
  RaisedButton,
  Card,
  CardActions,
} = require('material-ui');

const Login = React.createClass({
  onFormSubmit(e) {
   axios({
      method: 'post',
      data: {email: email, password: password},
      url: `${SERVER_HOST}/login`,
      withCredentials: true,
    })
    .then(response => {
      if (response.status !== 200)
        throw new Error('Error');
      else {
        //The call back from parent component
        this.props.submit();
      }
    })
    .catch(error => {
      this.setState({error: error});
    });
 },


  render() {
    return (
      <form onSubmit={this.onFormSubmit}>
       <fieldset>
        <CardActions>
          <RaisedButton
            label="Login!"
            type="submit" />
        </CardActions>
      </fieldset>
    </form>
    );
 }
});


const Main = React.createClass({
  onSubmitLogin: function() {
    //Call dropzone but will not open.
    this.refs.dropzone.open();
  },

  render() {
    return (
      <div>
        <Login
          submit={this.onSubmitLogin} />
        <Dropzone disableClick={true}  ref="dropzone" onDrop={this.onDrop.bind(this)}>
          <MyCard
           onClick={this.onUpload.bind(this)}
           img="images/upload.png"/>
        </Dropzone>
      </div>
    );
  }

});

```

**Comment by okonet** [comment] 2016-01-13 09:51
You forgot to bind `this.onSubmitLogin` to `this`

**Comment by bfwg** [comment] 2016-01-13 14:14
Hi, I just checked I did bind in my code 
```js
submit={this.onSubmitLogin.bind(this)}
```
and it's still not working.

**Comment by askbeka** [comment] 2017-02-02 01:32
Not working when disableClick set to true

**Comment by okonet** [comment] 2017-02-02 10:55
@askbeka mind creating a PR for this?

**Comment by okonet** [comment] 2017-02-02 10:56
@askbeka is this a separate issue or should I reopen this one? If it's not related, please create a new issue and a R that fixes it.

**Comment by bbthorntz** [comment] 2018-05-31 06:50
@okonet sorry to comment on a closed issue, but I've also encountered this problem.

Strangely, setting a longer delay in the `setTimeout` method of your example reproduces the problem. For example, increasing it from `1000ms` to `3000ms`.

Please see https://codesandbox.io/s/n7o91o9310 for a reproducible case.

**Comment by Nodman** [comment] 2018-06-01 13:21
@bbthorntz For security reasons browser blocks all the popups and dialogues that was opened not directly by user interaction, or those which were opened programmatically but with a delay not greater than 1000 ms. 
If 1000ms dealy is your usual case, then you probably want to rework  UI/UX flow somehow to prevent this, because I am pretty sure that there is no good workaround for this

Here some [proofs](https://codepen.io/anon/pen/pKjvvX?editors=1111)

**Comment by bbthorntz** [comment] 2018-06-01 14:14
@Nodman ahh, that’s it. Thanks for the info! Like you said, we realised it was probably better to rework the UI.

**Comment by okonet** [comment] 2018-06-01 21:09
It would be great to have it in docs I think. PR?

**Comment by Nodman** [comment] 2018-06-04 06:12
@okonet  good point, I'll do it!

**Comment by bbthorntz** [comment] 2018-06-04 06:17
I've been searching for an official documentation to link to but I can't find anything. It's strange that browsers (at least, Google Chrome) don't display a console warning to notify users that the event was blocked for security.

**Comment by Nodman** [comment] 2018-06-04 06:35
Strange indeed, Mozilla showing little notification about popup blocking while Safari and Chrome are staying silent.
I also wasn't able to find any docs on this, just some stack-overflow posts :(
