### ISSUE TITLE
activeClassName and rejectClassName not work

### ISSUE THREAD

**Issue by Sky161** [okonet/react-dropzone#418] opened 2017-04-26 10:18 UTC
Hello I use react-dropzone 3.13.0 and I have little problem. 'activeClassName' and 'rejectClassName' don't work. My component:

```
this.mimetypes = ['image/*', 'application/pdf', 'application/msword',
    'application/excel', 'application/vnd.ms-excel', 'application/x-excel', 'application/x-msexcel'];

handleDrop = (files) => {
		const newArrFile = this.state.files.slice();
		files.forEach(file => {
			newArrFile.push(file);
		});

		this.setState({
			files: newArrFile
		});
	}
<Dropzone
	className='request__dragdrop'
	name='files'
	onDrop={this.handleDrop}
	accept={this.mimetypes.join(',')}
	activeClassName='request__dragdrop_success'
	rejectClassName='request__dragdrop_error'>
	<p>Перетащите или нажмите на область для загрузки файлов</p>
</Dropzone>
```

**Comment by okonet** [comment] 2017-04-26 11:08
Please elaborate on "doesn't work". Best way to report issue is to create reproducible examples. 

Is a duplicate of #330 or #377?

I'm closing this one since it's not following the issue template.

**Closed by okonet** 2017-04-26 11:08 UTC
